name: Project seeks new maintainers! 
description: else archival planned by mid 2024
labels: 
body:
  - type: markdown
    attributes:
      value: |
        - ⚠️ This project has not had a release for ~2 years, another release is not planned. Rather, this project will be archived by mid 2024 unless someone else takes over maintenance. This is because:
        - > The driving force for forking—to have a community run icon set—has not been realized. The site and font build processes are broken. The source icon files need to be reworked or remade. The project focuses on icon fonts, despite icon fonts as a technology being outdated. Many other free icon sets now exist.
        - Read the full retrospective here. People interested in taking over maintenance can write in the matrix room mention me @douginamug in an issue or write to me on on mastodon. ⚠️

  - type: checkboxes
    attributes:
      label: Acknowledgement
      options:
        - label: I am aware that this issue will not be worked on unless other maintainers take over the project.
          required: true

  - type: textarea
    attributes:
      label: Issue body
      description: |
        Write the content of your issue here.